spring.redis.host: myelastic.8jkauu.0001.apn2.cache.amazonaws.com
spring.redis.port: 6379
spring.session.store-type: none
server.port: 5000

---
spring.profiles: prd
spring.redis.host: myelastic.8jkauu.0001.apn2.cache.amazonaws.com
spring.redis.port: 6379
spring.session.store-type: none