#spring.redis.host: 127.0.0.1
#spring.redis.port: 6379
#spring.session.store-type: none

---
spring.profiles: prd
spring.redis.host: test2.mrhbag.0001.apn2.cache.amazonaws.com
spring.redis.port: 6379
spring.session.store-type: none